### ISSUE TITLE
Any options to disable preview checkbox?

### ISSUE THREAD

**Issue by errbh** [Nigel2392/wagtail_ace_editor#1]
I was looking to disable preview checkbox by default. Is there any options for this?

**Comment by Nigel2392** [comment]
Give me a few days (4-ish max?) - simple change but have a lot going on
I'll add it for you.
If you have any other idea's, name a few; maybe I'll add more.

**Comment by Nigel2392** [comment]
Wasn't sure if you meant disable the preview entirely or the state of the checkbox itself.
Added both.

Preview can be disabled entirely with the `disable_preview` boolean argument to the widget/block/field.
Same goes for the checkbox state with `preview_chechbox_checked`

**Comment by errbh** [comment]
`disable_preview ` is exactly what I was looking for. Thank you so much :)
