### ISSUE TITLE
Block name not properly reflected in the editor section

### ISSUE THREAD

**Issue by errbh** [Nigel2392/wagtail_ace_editor#2]
On using `wagtail_ace_editor `like this:
```
body = StreamField([
        ('heading', blocks.CharBlock(form_classname="title")),
        ('paragraph', blocks.RichTextBlock()),
        ('image', ImageChooserBlock()),
        ('html', AceEditorBlock(mode = "ace/mode/html")),
        ('css', AceEditorBlock(mode = "ace/mode/css"))
    ], blank=True, null=True)
```
On the editor interface name of the blocks are not differentiated as it shows "Ace Editor" for both blocks like:
![image](https://github.com/Nigel2392/wagtail_ace_editor/assets/9290635/8ea49e84-9bb7-495d-949b-3e1a5d662825)

**Comment by Nigel2392** [comment]
Should be fixed in `1.1.6`.
